version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app-api:
    build: .
    restart: always
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000"
    volumes:
      - .:/app   # код меняем на лету

  app-worker:
    build: .
    restart: always
    depends_on:
      - db
    command: python worker.py
    volumes:
      - .:/app   # чтобы видеть изменения в reports.py

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  postgres_data: